<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE source [
        <!ELEMENT source (order+) >
        <!ELEMENT order (orderTime,deliveryData,directory) >
        <!ELEMENT orderTime (#PCDATA) >
        <!ELEMENT deliveryData (#PCDATA) >
        <!ELEMENT directory (content+) >
        <!ELEMENT content (partTypeID,partType,processing,time,amount) >
        <!ELEMENT partTypeID (#PCDATA) >
        <!ELEMENT partType (#PCDATA) >
        <!ELEMENT processing (#PCDATA) >
        <!ELEMENT time (#PCDATA) >
        <!ELEMENT amount (#PCDATA) >

        <!ATTLIST order id CDATA #REQUIRED>
        <!ATTLIST content id CDATA #REQUIRED>
        ]>

<source>
    <order id="1">
        <orderTime>0</orderTime>
        <deliveryData>800</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>300-150</time>
                <amount>2</amount>
            </content>
        </directory>
    </order>

    <order id="2">
        <orderTime>100</orderTime>
        <deliveryData>1000</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>555</partTypeID>
                <partType>unknown</partType>
                <processing>turning-milling-carving</processing>
                <time>350-200-200</time>
                <amount>2</amount>
            </content>
        </directory>
    </order>

    <!--紧急订单-->
    <order id="3">
        <orderTime>200</orderTime>
        <deliveryData>900</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>666</partTypeID>
                <partType>unknown</partType>
                <processing>turning-carving</processing>
                <time>120-200</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <order id="3">
        <orderTime>200</orderTime>
        <deliveryData>2500</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>666</partTypeID>
                <partType>unknown</partType>
                <processing>turning-carving-milling-special1</processing>
                <time>200-300-100-300</time>
                <amount>3</amount>
            </content>
        </directory>
    </order>

    <order id="4">
        <orderTime>200</orderTime>
        <deliveryData>1200</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>300-150</time>
                <amount>2</amount>
            </content>
            <content id="2">
                <partTypeID>2</partTypeID>
                <partType>axis</partType>
                <processing>turning-milling</processing>
                <time>400-150</time>
                <amount>1</amount>
            </content>
            <content id="3">
                <partTypeID>3</partTypeID>
                <partType>flange</partType>
                <processing>milling-turning-carving</processing>
                <time>200-200-250</time>
                <amount>2</amount>
            </content>
            <content id="4">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>350-200</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <order id="5">
        <orderTime>600</orderTime>
        <deliveryData>2200</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>444</partTypeID>
                <partType>unknow</partType>
                <processing>turning-carving</processing>
                <time>300-150</time>
                <amount>1</amount>
            </content>
            <content id="2">
                <partTypeID>2</partTypeID>
                <partType>axis</partType>
                <processing>turning-milling</processing>
                <time>400-150</time>
                <amount>1</amount>
            </content>
            <content id="3">
                <partTypeID>3</partTypeID>
                <partType>flange</partType>
                <processing>milling-turning-carving</processing>
                <time>200-200-250</time>
                <amount>1</amount>
            </content>
            <content id="4">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-special2</processing>
                <time>350-200</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <order id="6">
        <orderTime>1000</orderTime>
        <deliveryData>2000</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>340-180</time>
                <amount>2</amount>
            </content>
            <content id="2">
                <partTypeID>2</partTypeID>
                <partType>axis</partType>
                <processing>turning-milling</processing>
                <time>420-170</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <!--紧急订单-->
    <order id="7">
        <orderTime>1200</orderTime>
        <deliveryData>1800</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>5555</partTypeID>
                <partType>unknow</partType>
                <processing>turning-milling</processing>
                <time>200-180</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <order id="8">
        <orderTime>1300</orderTime>
        <deliveryData>2500</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>340-180</time>
                <amount>2</amount>
            </content>
            <content id="2">
                <partTypeID>2</partTypeID>
                <partType>axis</partType>
                <processing>turning-milling</processing>
                <time>420-170</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>

    <order id="9">
        <orderTime>1500</orderTime>
        <deliveryData>2500</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>1</partTypeID>
                <partType>plate</partType>
                <processing>milling-carving</processing>
                <time>340-180</time>
                <amount>2</amount>
            </content>
            <content id="2">
                <partTypeID>2</partTypeID>
                <partType>axis</partType>
                <processing>turning-milling</processing>
                <time>420-170</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>
</source>