<?xml version="1.0" encoding="UTF-8" ?>

<!--用以下格式定义订单
        Define the order in the following format-->

<!DOCTYPE source [
        <!ELEMENT source (order+) >
        <!ELEMENT order (orderTime,deliveryData,directory) >
        <!ELEMENT orderTime (#PCDATA) >
        <!ELEMENT deliveryData (#PCDATA) >
        <!ELEMENT directory (content+) >
        <!ELEMENT content (partTypeID,partType,processing,time,amount) >
        <!ELEMENT partTypeID (#PCDATA) >
        <!ELEMENT partType (#PCDATA) >
        <!ELEMENT processing (#PCDATA) >
        <!ELEMENT time (#PCDATA) >
        <!ELEMENT amount (#PCDATA) >

        <!ATTLIST order id CDATA #REQUIRED>
        <!ATTLIST content id CDATA #REQUIRED>
        ]>

<source>
    <order id="1">
        <orderTime>0</orderTime>
        <deliveryData>2000</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>555</partTypeID>
                <partType>unknow</partType>
                <processing>turning-carving</processing>
                <time>150-200</time>
                <amount>1</amount>
            </content>
            <content id="2">
                <partTypeID>555</partTypeID>
                <partType>unknow</partType>
                <processing>turning-carving</processing>
                <time>300-250</time>
                <amount>2</amount>
            </content>
            <content id="3">
                <partTypeID>3</partTypeID>
                <partType>flange</partType>
                <processing>milling-turning-carving</processing>
                <time>200-250-250</time>
                <amount>1</amount>
            </content>
            <content id="4">
                <partTypeID>3</partTypeID>
                <partType>flange</partType>
                <processing>milling-turning-carving</processing>
                <time>200-200-250</time>
                <amount>2</amount>
            </content>
            <content id="5">
                <partTypeID>555</partTypeID>
                <partType>unknown</partType>
                <processing>milling-turning</processing>
                <time>350-200</time>
                <amount>2</amount>
            </content>
        </directory>
    </order>

    <!--紧急订单-->
    <order id="2">
        <orderTime>200</orderTime>
        <deliveryData>900</deliveryData>
        <directory>
            <content id="1">
                <partTypeID>666</partTypeID>
                <partType>unknown</partType>
                <processing>milling-turning-carving</processing>
                <time>220-200-120</time>
                <amount>1</amount>
            </content>
            <content id="1">
                <partTypeID>666</partTypeID>
                <partType>unknown</partType>
                <processing>milling-carving-turning</processing>
                <time>140-200-120</time>
                <amount>1</amount>
            </content>
        </directory>
    </order>



</source>